import { BeltRequirements } from 'models/BeltRequirements/BeltRequirements';

export const mockBeltRequirements: BeltRequirements[] = [
  {
    beltOrder: 1,
    beltRank: 'White',
    forms: [],
    stances: ['ready', 'straddle', 'front', 'fighting', 'bowing'],
    blocks: ['low', 'knife_hand'],
    punches: ['center', 'reverse', 'jab'],
    kicks: ['front', 'round', 'stepping_kick', 'slide_up_kick'],
    jumps: [],
    falling: ['backwards'],
    oneSteps: [],
    selfDefense: [],
    comments:
      'Reasons for Kiai: More power, Not get air knocked out, Scare opponent, Clear mind, Draw attentio]',
    color: '#FFFFFF',
    textColor: '#000000',
  },
  {
    beltOrder: 2,
    beltRank: 'Gold White',
    forms: [],
    stances: ['back'],
    blocks: ['high'],
    punches: [],
    kicks: ['side'],
    jumps: ['jump_phase_1'],
    falling: ['forwards'],
    oneSteps: [],
    selfDefense: [],
    comments: '',
    color: '#FFD700',
    textColor: '#000000',
  },
  {
    beltOrder: 3,
    beltRank: 'Gold',
    forms: ['geicho_hyung_il_bu'],
    stances: ['shifting'],
    blocks: ['inside'],
    punches: [],
    kicks: [],
    jumps: [],
    falling: ['forward_roll'],
    oneSteps: [],
    selfDefense: [],
    comments: '1st half of Geicho Hyung Il Bu, Begin sparring',
    color: '#FFD700',
    textColor: '#000000',
  },
  {
    beltOrder: 4,
    beltRank: 'Gold Black',
    forms: ['geicho_hyung_il_bu'],
    stances: [],
    blocks: ['block_punch'],
    punches: [],
    kicks: ['spin_back'],
    jumps: ['jump_phase_2'],
    falling: [],
    oneSteps: [],
    selfDefense: [],
    comments: 'All of  Geicho Hyung Il Bu',
    color: '#DAA520',
    textColor: '#FFFFFF',
  },
];
