name: Backend CI for Railway

on:
  push:
    branches: [main, staging]
    paths: ["BackEnd/**"]
  pull_request:
    branches: [main]
    paths: ["BackEnd/**"]

env:
  NODE_VERSION: "18"

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: BackEnd/package-lock.json

      - name: Install dependencies
        working-directory: ./BackEnd
        run: npm ci

        # 
      # - name: Run tests
      #   working-directory: ./BackEnd
      #   run: npm run test -- --passWithNoTests

      - name: Build application
        working-directory: ./BackEnd
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
          path: |
            BackEnd/dist/
            BackEnd/package.json
            BackEnd/package-lock.json
