name: Backend Tests with Coverage

on:
  pull_request:
    paths:
      - "BackEnd/**"

permissions:
  contents: read
  pull-requests: write

env:
  NODE_VERSION: "20"

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: BackEnd/package-lock.json

      - name: Install dependencies
        working-directory: ./BackEnd
        run: npm ci

      - name: Run tests with coverage
        working-directory: ./BackEnd
        run: npm run test:coverage:ci

      - name: Show coverage output (debug)
        if: always()
        working-directory: ./BackEnd
        run: |
          echo "Coverage directory listing:" || true
          ls -al coverage || true

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: BackEnd/coverage

      - name: Upload coverage summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-summary
          path: BackEnd/coverage/**

      - name: Check coverage threshold
        working-directory: ./BackEnd
        run: |
          THRESHOLD=30
          SUMMARY_JSON=coverage/coverage-summary.json
          FINAL_JSON=coverage/coverage-final.json
          if [ -f "$SUMMARY_JSON" ]; then
            # Only enforce statements/functions/lines - skip branches due to NestJS decorators
            node -e "const fs=require('fs');const t=${THRESHOLD};const s=JSON.parse(fs.readFileSync('$SUMMARY_JSON'));const total=s.total||s;const metrics=['statements','functions','lines'];let ok=true;metrics.forEach(m=>{const pct=total[m]&&total[m].pct?total[m].pct:0; if(pct < t){console.error(m+' coverage '+pct+'% < '+t+'%'); ok=false}}); if(!ok){process.exit(1);} else {console.log('Coverage threshold met');}"
          elif [ -f "$FINAL_JSON" ]; then
            node -e "const fs=require('fs');const t=${THRESHOLD};const s=JSON.parse(fs.readFileSync('$FINAL_JSON'));let totals={statements:{total:0,covered:0},functions:{total:0,covered:0},lines:{total:0,covered:0}};Object.values(s).forEach(f=>{if(f.statements){totals.statements.total+=f.statements.total||0;totals.statements.covered+=f.statements.covered||0;} if(f.functions){totals.functions.total+=f.functions.total||0;totals.functions.covered+=f.functions.covered||0;} if(f.lines){totals.lines.total+=f.lines.total||0;totals.lines.covered+=f.lines.covered||0;}});let ok=true;['statements','functions','lines'].forEach(m=>{const tot=totals[m].total;const cov=totals[m].covered;const pct=tot>0?Math.round((cov/tot)*100*100)/100:100; if(pct < t){console.error(m+' coverage '+pct+'% < '+t+'%'); ok=false}}); if(!ok){process.exit(1);} else {console.log('Coverage threshold met');}"
          else
            echo "No coverage JSON found (coverage-summary.json or coverage-final.json)" >&2
            exit 1
          fi

      - name: Create coverage markdown
        if: always()
        working-directory: ./BackEnd
        run: |
          if [ -f "coverage/coverage-summary.json" ]; then
            # Create a simple coverage report
            echo "# Backend Coverage Report" > coverage_report.md
            echo "" >> coverage_report.md

            # Extract total coverage (excluding branches due to NestJS decorators)
            STMT_PCT=$(node -e "const s=JSON.parse(require('fs').readFileSync('coverage/coverage-summary.json'));console.log(s.total.statements.pct)")
            FUNC_PCT=$(node -e "const s=JSON.parse(require('fs').readFileSync('coverage/coverage-summary.json'));console.log(s.total.functions.pct)")
            LINE_PCT=$(node -e "const s=JSON.parse(require('fs').readFileSync('coverage/coverage-summary.json'));console.log(s.total.lines.pct)")

            echo "## Overall Coverage" >> coverage_report.md
            echo "" >> coverage_report.md
            echo "| Metric | Coverage |" >> coverage_report.md
            echo "|--------|----------|" >> coverage_report.md
            echo "| Statements | ${STMT_PCT}% |" >> coverage_report.md
            echo "| Functions | ${FUNC_PCT}% |" >> coverage_report.md
            echo "| Lines | ${LINE_PCT}% |" >> coverage_report.md
            echo "" >> coverage_report.md
            echo "✅ All backend tests passed!" >> coverage_report.md
          else
            echo "# Backend Coverage Report" > coverage_report.md
            echo "" >> coverage_report.md
            echo "No coverage summary found." >> coverage_report.md
          fi

      - name: Read coverage report
        id: read_coverage
        if: always()
        working-directory: ./BackEnd
        run: |
          if [ -f coverage_report.md ]; then
            # Use a more robust delimiter and escape special characters
            DELIMITER="EOF_$(date +%s)"
            echo "comment<<$DELIMITER" >> $GITHUB_OUTPUT
            cat coverage_report.md >> $GITHUB_OUTPUT
            echo "$DELIMITER" >> $GITHUB_OUTPUT
          else
            echo "comment=No backend coverage report generated." >> $GITHUB_OUTPUT
          fi

      - name: Post coverage comment to PR
        # Skip posting comment for forked PRs because secrets/GITHUB_TOKEN are not available
        if: always() && (github.event.pull_request.head.repo.fork == false)
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Backend coverage results for this PR:

            ${{ steps.read_coverage.outputs.comment }}
