name: Frontend Tests with Coverage

on:
  pull_request:
    paths:
      - "FrontEnd/**"

# Note: For PRs from forked repositories, the GITHUB_TOKEN has limited permissions
# and cannot post comments. To allow comments for forked PRs, use a repo PAT
# stored in a secret and pass it to the comment step, or use a separate
# workflow triggered by pull_request_target with careful security checks.

permissions:
  contents: read
  pull-requests: write

env:
  NODE_VERSION: "18"

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: FrontEnd/package-lock.json

      - name: Install dependencies
        working-directory: ./FrontEnd
        run: npm ci

      - name: Run tests with coverage
        working-directory: ./FrontEnd
        # Use project's test:ci script which runs jest with --ci and coverage
        run: npm run test:ci

      - name: Show coverage output (debug)
        if: always()
        working-directory: ./FrontEnd
        run: |
          echo "Coverage directory listing:" || true
          ls -al coverage || true

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: front-end-coverage
          path: FrontEnd/coverage

      - name: Upload coverage summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: front-end-coverage-summary
          path: FrontEnd/coverage/**

      - name: Check coverage threshold
        if: always()
        working-directory: ./FrontEnd
        run: |
          THRESHOLD=30
          SUMMARY_JSON=coverage/coverage-summary.json
          FINAL_JSON=coverage/coverage-final.json
          if [ -f "$SUMMARY_JSON" ]; then
            # Only enforce statements/functions/lines - skip branches
            node -e "const fs=require('fs');const t=${THRESHOLD};const s=JSON.parse(fs.readFileSync('$SUMMARY_JSON'));const total=s.total||s;const metrics=['statements','functions','lines'];let ok=true;metrics.forEach(m=>{const pct=total[m]&&total[m].pct?total[m].pct:0; if(pct < t){console.error(m+' coverage '+pct+'% < '+t+'%'); ok=false}}); if(!ok){process.exit(1);} else {console.log('Coverage threshold met');}"
          elif [ -f "$FINAL_JSON" ]; then
            node -e "const fs=require('fs');const t=${THRESHOLD};const s=JSON.parse(fs.readFileSync('$FINAL_JSON'));let totals={statements:{total:0,covered:0},functions:{total:0,covered:0},lines:{total:0,covered:0}};Object.values(s).forEach(f=>{if(f.statements){totals.statements.total+=f.statements.total||0;totals.statements.covered+=f.statements.covered||0;} if(f.functions){totals.functions.total+=f.functions.total||0;totals.functions.covered+=f.functions.covered||0;} if(f.lines){totals.lines.total+=f.lines.total||0;totals.lines.covered+=f.lines.covered||0;}});let ok=true;['statements','functions','lines'].forEach(m=>{const tot=totals[m].total;const cov=totals[m].covered;const pct=tot>0?Math.round((cov/tot)*100*100)/100:100; if(pct < t){console.error(m+' coverage '+pct+'% < '+t+'%'); ok=false}}); if(!ok){process.exit(1);} else {console.log('Coverage threshold met');}"
          else
            echo "No coverage JSON found (coverage-summary.json or coverage-final.json)" >&2
            exit 1
          fi

      - name: Create coverage markdown
        if: always()
        working-directory: ./FrontEnd
        run: |
          echo "# Frontend Coverage Report" > coverage_report.md || true
          SUMMARY_JSON=coverage/coverage-summary.json
          FINAL_JSON=coverage/coverage-final.json
          if [ -f "$SUMMARY_JSON" ]; then
            node -e "const fs=require('fs');const s=JSON.parse(fs.readFileSync('$SUMMARY_JSON'));const rows=Object.entries(s).map(([k,v])=>`| ${k} | ${v.statements.pct}% | ${v.branches.pct}% | ${v.functions.pct}% | ${v.lines.pct}% |`);const header='| File | Stmts | Branch | Funcs | Lines |\n|---|---:|---:|---:|---:';fs.writeFileSync('coverage_report.md', '# Frontend Coverage Report\n\n'+header+'\n'+rows.join('\n'));"
          elif [ -f "$FINAL_JSON" ]; then
            # Prefer the repository script which produces a nicer table and totals
            node ./scripts/coverage-to-md.js "$FINAL_JSON" > coverage_table.md || true
            echo "# Frontend Coverage Report" > coverage_report.md || true
            cat coverage_table.md >> coverage_report.md || true
          elif [ -f coverage/coverage-summary.txt ]; then
            echo "\n\n<details><summary>Coverage summary</summary>" >> coverage_report.md || true
            cat coverage/coverage-summary.txt >> coverage_report.md || true
            echo "</details>" >> coverage_report.md || true
          else
            echo "No coverage summary found" >> coverage_report.md || true
          fi

      - name: Read coverage report
        id: read_coverage
        if: always()
        working-directory: ./FrontEnd
        run: |
          if [ -f coverage_report.md ]; then
            echo "comment<<EOF" >> $GITHUB_OUTPUT
            cat coverage_report.md >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "comment<<EOF" >> $GITHUB_OUTPUT
            echo "No coverage report generated." >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi

      - name: Post coverage comment to PR
        # Skip posting comment for forked PRs because secrets/GITHUB_TOKEN are not available
        if: always() && (github.event.pull_request.head.repo.fork == false)
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Coverage results for this PR:

            ${{ steps.read_coverage.outputs.comment }}
